<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="org.ossmeter.metricprovider.generic.numberofinvalidbugzillabugs.model">
  <eClassifiers xsi:type="ecore:EClass" name="DailyNoib">
    <eAnnotations source="viz">
      <details key="target" value="gcharts"/>
      <details key="chart" value="line"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bugzillas" upperBound="-1" eType="//DailyBugzillaData" containment="true">
      <eAnnotations source="series"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DailyBugzillaData">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="numberOfInvalidBugs">
      <eAnnotations source="yaxis">
        <details key="title" value="Number of invalid bugs"/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eStructuralFeatures>
  </eClassifiers>
</ecore:EPackage>
