<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="org.ossmeter.metricprovider.trans.dailyrequestsreplies.model">
  <eClassifiers xsi:type="ecore:EClass" name="DailyRequestsReplies">
    <eAnnotations source="viz">
      <details key="target" value="gcharts"/>
      <details key="chart" value="bar"/>
    </eAnnotations>
    <eAnnotations source="db">
      <details key="qualifiedCollectionNames" value="true"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dayArticles" upperBound="-1" eType="//DayArticles" containment="true">
      <eAnnotations source="series">
        <details key="label" value="articles"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dayReplies" upperBound="-1" eType="//DayReplies" containment="true">
      <eAnnotations source="series">
        <details key="label" value="replies"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dayRequests" upperBound="-1" eType="//DayRequests" containment="true">
      <eAnnotations source="series">
        <details key="label" value="requests"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DayArticles">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name">
      <eAnnotations source="searchable"/>
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="numberOfArticles">
      <eAnnotations source="yaxis">
        <details key="title" value="Number of articles"/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DayRequests">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name">
      <eAnnotations source="searchable"/>
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="numberOfRequests">
      <eAnnotations source="yaxis">
        <details key="title" value="Number of requests"/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DayReplies">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name">
      <eAnnotations source="searchable"/>
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="numberOfReplies">
      <eAnnotations source="yaxis">
        <details key="title" value="Number of replies"/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eStructuralFeatures>
  </eClassifiers>
</ecore:EPackage>
