<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="com.googlecode.pongo.tests.stubs.model">
  <eClassifiers xsi:type="ecore:EClass" name="GoogleCode">
    <eAnnotations source="db"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="projects" upperBound="-1" eType="//GoogleProject" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="developers" upperBound="-1" eType="//Developer" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GoogleProject" eSuperTypes="//Project">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="developers" upperBound="-1" eType="//Developer"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Project">
    <eAnnotations source="stub">
      <details key="javaClass" value="com.googlecode.pongo.tests.stubs.model.ProjectFromAnotherLibrary"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Developer">
    <eAnnotations source="stub">
      <details key="javaClass" value="com.googlecode.pongo.tests.stubs.model.DeveloperFromAnotherLibrary"/>
    </eAnnotations>
  </eClassifiers>
</ecore:EPackage>
