<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="org.ossmeter.metricprovider.historic.avgnumberofrequestsreplies.model">
  <eClassifiers xsi:type="ecore:EClass" name="AverageRR">
    <eAnnotations source="viz">
      <details key="target" value="gcharts"/>
      <details key="chart" value="line"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="articles" upperBound="-1" eType="//ArticleData" containment="true">
      <eAnnotations source="series">
        <details key="label" value="articles"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="requests" upperBound="-1" eType="//RequestData" containment="true">
      <eAnnotations source="series">
        <details key="label" value="requests"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="replies" upperBound="-1" eType="//ReplyData" containment="true">
      <eAnnotations source="series">
        <details key="label" value="replies"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ArticleData">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="averageArticles">
      <eAnnotations source="yaxis">
        <details key="title" value="Average number of articles"/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RequestData">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="averageRequests">
      <eAnnotations source="yaxis">
        <details key="title" value="Average number of requests"/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ReplyData">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="averageReplies">
      <eAnnotations source="yaxis">
        <details key="title" value="Average number of replies"/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    </eStructuralFeatures>
  </eClassifiers>
</ecore:EPackage>
