<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="org.ossmeter.metricprovider.historic.numberofrequestsrepliesperdaypernewsgroup.model">
  <eClassifiers xsi:type="ecore:EClass" name="DailyNorr">
    <eAnnotations source="viz">
      <details key="target" value="gcharts"/>
      <details key="chart" value="line"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="requests" upperBound="-1" eType="//DailyNewsgroupRequestsData" containment="true">
      <eAnnotations source="series">
        <details key="label" value="requests"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="replies" upperBound="-1" eType="//DailyNewsgroupRepliesData" containment="true">
      <eAnnotations source="series">
        <details key="label" value="replies"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DailyNewsgroupData" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="url_name">
      <eAnnotations source="searchable"/>
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DailyNewsgroupRequestsData" eSuperTypes="//DailyNewsgroupData">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="numberOfRequests">
      <eAnnotations source="yaxis">
        <details key="title" value="Number of occurences"/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DailyNewsgroupRepliesData" eSuperTypes="//DailyNewsgroupData">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="numberOfReplies">
      <eAnnotations source="yaxis">
        <details key="title" value="Number of occurences"/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eStructuralFeatures>
  </eClassifiers>
</ecore:EPackage>
