<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="org.ossmeter.metricprovider.rascal.historic.model">
  <eClassifiers xsi:type="ecore:EClass" name="RascalHistoricMetrics">
    <eStructuralFeatures xsi:type="ecore:EReference" name="measurements" upperBound="-1" containment="true">
      <eType xsi:type="ecore:EClass" href="platform:/resource/org.ossmeter.platform-extensions.platform.metricmanager.rascal/src/org/ossmeter/metricprovider/rascal/trans/model/RascalMetrics.ecore#//Measurement"/>
    </eStructuralFeatures>
  </eClassifiers>
</ecore:EPackage>
